export { Dashboard } from './Dashboard'
export { Horarios } from './Horarios'
export { Insumos } from './Insumos'
export { Equipos } from './Equipos'
export { Incidencias } from './Incidencias'
export { default as ReportesSimple } from './ReportesSimple'
export { ComparacionInsumos } from './ComparacionInsumos'
export { Configuracion } from './Configuracion' 