export { Dashboard } from './Dashboard'
export { Laboratorios } from './Laboratorios'
export { Docentes } from './Docentes'
export { Horarios } from './Horarios'
export { Insumos } from './Insumos'
export { Equipos } from './Equipos'
export { Incidencias } from './Incidencias'
export { default as ReportesSimple } from './ReportesSimple' 